### ISSUE TITLE
Is 40% of B0 really a 'target'?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#213] opened 2017-01-25 19:31 UTC
Page 15 last year (top paragraph) says "The median female spawning biomass was above target until 1998 ... ". 

This was the first mention of a biomass target. I just want to clarify that it is a target, not just something we want to stay above (which 10% of B0 is). 

Caption of Figure 4 says that the management target is defined in the Agreement - I couldn't quite see the biomass target explicitly defined. But is it just implicitly defined once the management target is defined?

I'll probably be able to answer this myself when I go through the definitions more carefully (and probably look at some issues from last year), but for now just flagging it.

**Comment by taylori** [comment] 2017-01-25 19:59
No, I believe that 40% of B0 is not a "target", just a reference point associated with an adjustment to the TAC below the F-40% fishing mortality rate.

The following clips are from the treaty: http://www.westcoast.fisheries.noaa.gov/publications/fishery_management/groundfish/whiting/whiting-treaty.pdf
![image](https://cloud.githubusercontent.com/assets/4992918/22306809/85e9dfa4-e2f5-11e6-9d01-96cffeb8163a.png)

...

![image](https://cloud.githubusercontent.com/assets/4992918/22306799/7727995c-e2f5-11e6-8a75-0f047c421c39.png)

**Comment by aaronmberger** [comment] 2017-01-25 20:10
Yeah, let's stick with 40% of B0 being a management reference point, not a target (even though I'm not personally keen on these generic specifications, but it is in the treaty).  It really is used to 'trigger' a change in the way total TAC is specified in relation to spawning biomass (i.e., different slope in the 40/10 control rule).

**Comment by taylori** [comment] 2017-01-26 01:54
In the recent commit (df03823), I removed the "Management target" label on the line at 0.4 in the figures comparing stock status for different models (such as Fig 46). That label remains on the figures showing fishing intensity in units of SPR, which I think is appropriate. This change will presumably require cleaning out your knitr-cache to see.

**Comment by andrew-edwards** [comment] 2017-01-26 17:12
I can go through and look for consistency (at some point). Yes, reference point is definitely more appropriate. There are a few concepts that are described in multiple ways - I think this year we have time to improve consistency.

**Comment by andrew-edwards** [comment] 2017-01-26 20:23
So I think this is wrong in the Introduction:

"Since 1999, catch targets have been determined using an $\Fforty$ default harvest rate with a 40:10 adjustment that decreases the catch linearly from the catch target at a relative spawning biomass of 40\% and above, to zero catch at relative spawning biomass values of 10\% or less (called the default harvest policy in the Agreement)."

Because 'relative spawning biomass' is defined as B/B0 in the glossary. I think 'relative spawning biomass of 40%' should be B_{SPR=40%}  , though I think that definition is wrong in the glossary also. I thought B_{40%} was 0.4B_0.

Think it best to change all these in one go to ensure consistency.

**Comment by andrew-edwards** [comment] 2017-01-26 20:25
See issue #179 also where we discussed this.

**Comment by taylori** [comment] 2017-01-26 21:14
The problem is that B_{SPR=40%} could be calculated at an equilibrium, but for any given year, there's no single biomass associated with an SPR=40% because it would depend on the selectivity of the fishery.

Figure h (same as Figure 36) highlights the need for 2 dimensions to measure what's going on: one related to biomass and one related to fishing. 

I think it makes sense for the fishing-related dimension to be measured relative to the target in the treaty, which is SPR=40%. 

The treaty doesn't specify a biomass target, just 2 reference points associated with adjustments to the TAC away from the F_SPR=40% target harvest rate. The treaty defines "40/10 adjustment" in terms of the biomass falling below "40 percent of its unfished level" and "10 percent of its unfished level", so I think that expressing the biomass dimension as the biomass relative the unfished level is most useful for understanding stock status in the same units as the 40/10 adjustment.

Also, I think that stock assessments have been reporting spawning biomass relative to B0 for decades.

**Comment by andrew-edwards** [comment] 2017-01-26 21:49
Thanks - that really helped, especially reference to Figure h. So the harvest control rule would be a line
      _____ 
___/

where the inflection points are (0.4,1) and (0.1,0) on Figure h.

The confusing thing was that there are two 40% things floating around they're not the same. But I think I'm getting how the time-varying selectivity makes it impossible (?) to make the x-axis of Figure h in terms of B_{SPR=40%}.

Suggest we carefully fix the Glossary first, and then work through the text.

**Comment by taylori** [comment] 2017-01-26 21:54
Sorry I've been so slow to make my contributions to the glossary (issue #179). I will work on that now.

**Comment by taylori** [comment] 2017-01-27 21:48
Glossary now improved, including new figure.  If those things seem OK, we can probably close this issue and just keep an eye out for text that doesn't match as we read through the document.

**Comment by aaronmberger** [comment] 2017-01-27 21:50
sounds good, closing

**Closed by aaronmberger** 2017-01-27 21:50 UTC
