### ISSUE TITLE
Incorporate Jaclyn's edits (suggestions and clarifications) for 2019

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#453] opened 2018-03-09 22:00 UTC
Simply ran out of time to get to them in 2018. I have them on a printout.

**Comment by kellijohnson** [comment] 2018-10-11 00:48
Any chance you can scan them and attach them to this issue?

**Comment by andrew-edwards** [comment] 2018-10-11 21:07
Good idea, though they're just on a printout of the whole assessment, so not really practical. They weren't major, mainly for clarity; I can easily do them for next time (especially as she's reviewing again).

**Comment by kellijohnson** [comment] 2018-10-24 23:07
Thanks @andrew-edwards that will be great.

**Comment by andrew-edwards** [comment] 2019-02-07 00:21
I started looking at these a few weeks ago. Mainly minor (think I did some), but one question was why is the spawning biomass females only (in herring they do males and females)?

Similarly, should probably clarify somewhere that it's a one-sex model because [presumably] there is little difference between male and female growth? A reference would be nice.

**Comment by aaronmberger** [comment] 2019-02-07 19:31
Yes on sex model - does our reference to the growth work done in the 2011 assessment say anything about growth by sex (or only through time)?  Below is what it says and their justification.  I think this stuff got slowly taken out year after year as the document grew due to other things.  We cite this growth work, but that's about it.
![growth_2011assessment](https://user-images.githubusercontent.com/7946234/52437467-d3b39480-2acb-11e9-881e-70752d39857f.png)


[In both 2011 assessment models and in models used for management prior to the 2006
stock assessment, variability in length-at-age was included in stock assessments via the
calculation of empirical weight-at-age. In the 2006 and subsequent assessments that attempted to
estimate the parameters describing a parametric growth curve, strong patterns have been
identified in the observed data indicating sexually dimorphic and temporally variable growth.
Synthesis models in recent years have not explicitly accounted for sex-specific patterns (although
they have been documented repeatedly) but have allowed for the dramatic decline in maximum
size and corresponding increase in growth rate observed in the data (Figure 7). Parametric
growth models fit externally to data collected prior to 1990 and afterward show the same
dramatically different rates of growth for both sexes that has been estimated inside the SS model
in recent years (Figure 14). Hake show very rapid growth at younger ages, clearly evident in
data partitioned into seasons within each year (Figures 15 and 16). The trajectories of individual
cohorts also vary greatly, as has been documented in previous assessments.
In aggregate, these patterns result in a great amount of process error for length at age
relative to commonly employed parametric growth models. This means that even complex
approaches to modeling growth (and therefore fitting to length or age-at-length data explicitly)
will have great difficulty in making predictions that mimic the observed data. This has been
particularly evident in the residuals to the length-frequency data from recent SS models. We
investigated models that allow for a high degree of complexity in the growth process and fit to
length and age-at-length data in preparation for this assessment, but poor residual patterns
persisted in all cases (Figure 17).]

**Comment by aaronmberger** [comment] 2019-02-07 19:33
We typically do SSB based on just females, the only time most folks consider SSB based on males and females (for us anyway) is with rockfish or other species where's males nest guard.  To do a male and female SSB we would need a male maturity curve, and the NWFSC just started collecting some testes in 2018.

**Comment by andrew-edwards** [comment] 2019-02-08 16:41
Do @kellijohnson or @aaronmberger want to write a sentence or two summarising the above, thanks!

I'll skim through the rest of Jaclyn's edits if time, but that was the only major one (and I did some a while back), and she said there was nothing major....

**Comment by kellijohnson** [comment] 2019-02-08 17:17
I can. What section or line will it go in?

**Comment by aaronmberger** [comment] 2019-02-08 17:26
The executive summary says we retain the structural from of the 2018 model so I don't think we need more specifics there. So I was thinking just a couple of sentences in section 3.2 - Description of the base model, covering that it is a single sex model.  

RE: "because [presumably] there is little difference between male and female growth? A reference would be nice." - it actually is the opposite, the 2011 assessment found significant variation in growth through time and by sex, but they reference the incredible amount of variation (and time and time again bad residual patterns for all sorts of growth parameterizations) as why the wt-at-age approach was used (parsimony really) - so could cite the 2011 assessment document.  - much of this is already in section 2.3.4 though.  So maybe just add the single sex model part....

**Comment by aaronmberger** [comment] 2019-02-08 17:30
maybe just after first sentence of 3.2.  - mention that the model is a gender and fleet aggregated, single-area statistical catch-at-age model - or something like that and call it good.

**Comment by kellijohnson** [comment] 2019-02-08 17:53
Okay I am going to add the following to 3.2 after the first sentence:
The statistical-catch-at-age model assumes that the Pacific Hake population is a single coast-wide stock subject to one fleet with similar male and female population dynamics.

**Comment by aaronmberger** [comment] 2019-02-08 18:00
Changed two words.... we must be getting close to the deadline b/c getting nit picky...

The statistical-catch-at-age model assumes that the Pacific Hake population is a single coast-wide stock subject to one aggregated fleet with combined male and female population dynamics.

**Comment by andrew-edwards** [comment] 2019-02-08 19:44
Thanks Kelli.

Couple of Jaclyn's points for clarification (someone want to pick this off as I'm not quite sure of the answers, thanks):

1. page 7, line 6:  "Discard from all fisheries is estimated to be less than 1% of landings in recent years." Clarify which fisheries (esp. in context of preceding sentence).

2. page 10: " The subsequent decline is from the 2010 year class surpassing the age at which gains in
weight from growth are greater than the loss in weight from natural mortality." Clarify sentence, and delete 'natural'.  I agree... think deleting natural is enough.

Actually, that's it. The others (based on 2018 assesment) are done anyway during the updating...

**Comment by aaronmberger** [comment] 2019-02-08 19:50
Re the equilibrium question, I just talked to Ian and he confirmed my thoughts on this.  It is really quite convoluted (not easy to describe) due to early year (1946-1969) rec devs.  SS defines equilibrium virgin biomass as 'true' equilibrium (i.e., not adjustments using early year rec devs) despite putting those values in year 1964.  So let's not address the equilibrium thing now in the document, but we (or I) can speak to it at the meeting if someone brings it up.

**Comment by aaronmberger** [comment] 2019-02-08 19:55
I'll work on #1.

RE #2, can we do "The subsequent decline from 2014 to 2016 is primarily from the 2010 year class surpassing the age at which gains in weight from growth are greater than the loss in weight from mortality." I agree with removing natural mortality, though from Table 25 M is the most important but F in there too of course.

**Comment by kellijohnson** [comment] 2019-02-08 19:58
Regarding # 1, can't we just change it to
"Discard from all fisheries, including those that don't target hake, is estimated to be less than 1% of landings in recent years."

**Comment by andrew-edwards** [comment] 2019-02-08 20:01
Thanks - I think both are good. @aaronmberger want to do them. (Should 'loss' be losses'?).

**Comment by aaronmberger** [comment] 2019-02-08 20:10
changed to: "The subsequent decline from 2014 to 2016 is primarily
from the 2010 year class surpassing the age at which gains in weight from growth
are greater than the loss in weight from mortality."  so I think loss works here

**Comment by aaronmberger** [comment] 2019-02-08 20:10
Andy said that's it so closing...

**Closed by aaronmberger** 2019-02-08 20:10 UTC
