### ISSUE TITLE
switch to SS version 3.30.10

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#309] opened 2018-01-12 01:42 UTC
Stock Synthesis version 3.30.10 has some refinements to the time-varying selectivity options that we may want to explore. I've just added a "2018.05_change_to_SSv3.30.10" model to the Google Drive folder that uses the new executable (posted earlier today to https://vlab.ncep.noaa.gov/group/stock-synthesis/document-library). Re-installing r4ss from GitHub is necessary to work with this version, and it's possible that there may be changes needed to the document to deal with a few minor changes in labels or variable names. If so, it shouldn't be too hard to debug.

**Comment by andrew-edwards** [comment] 2018-01-19 18:34
So we don't need to upload a new SS version do we, because you have it appearing in each models/ directory anyway?

**Comment by taylori** [comment] 2018-01-19 18:37
Yes, I think that's correct.
Note that the directories uploaded yesterday (2018.11 through 2018.18) are
using 3.30.10 dated January 9, while the earlier ones used version 3.30.08.
Also, I ran the clean.bat file (also located in each directory) to clear
out unnecessary ADMB files. I don't believe any of those files are needed
for the document, but if their absence is an issue, we can always re-run
the model and modify clean.bat.

**Comment by andrew-edwards** [comment] 2018-01-19 18:42
Thanks. We only specifify the SS version in to the first two decimal places (line 45 of model-setup.r), currently set at 3.24 as we have a switch later to tell it to use 3.30 depending on the version number. Currently trying to get it working. Hopefully we don't need further switches depending on the later decimal places ;)

And do I have to re-install r4ss from last week? From it's readme  I have: r4ss 1.29.1 (January 11, 2018)

**Comment by taylori** [comment] 2018-01-19 18:59
Correct, you don't yet have to re-install r4ss. Version 1.29.1 (January 11, 2018) is the latest version in the master.
If we want to switch to the Dirichlet-Multinomial likelihood for the age comps, we would need to install the "development" branch of r4ss (as discussed at https://github.com/r4ss/r4ss/issues/129#issuecomment-358468468) or have me merge that branch into the trunk and reinstall the trunk. My hope was to do a bit more testing before merging those changes.

I would suggest that the switch to Dirichlet-Multinomial likelihood or alternative selectivity parameterization should only be considered if the U.S. government stays open past midnight tonight.

**Comment by andrew-edwards** [comment] 2018-01-19 19:25
With the new 2018.18_temporary_base  model (slightly newer version of SS) 
```build(T, T, T)```
gets an error, which I've traced to
```model$par <- readLines(par.fn)```
which is on line 50 of load-models.r.

Any quick ideas? I'll keep plugging away. You'll need to fetch my model2018.18 branch to get it running.

**Comment by andrew-edwards** [comment] 2018-01-19 19:27
readLines() is only:
```> readLines
function (con = stdin(), n = -1L, ok = TRUE, warn = TRUE, encoding = "unknown", 
    skipNul = FALSE) 
{
    if (is.character(con)) {
        con <- file(con, "r")
        on.exit(close(con))
    }
    .Internal(readLines(con, n, ok, warn, encoding, skipNul))
}```
and the error I get is 
```Error in file(con, "r") : invalid 'description' argument```

Didn't happen yesterday (with earlier model run, but still 3.30), so likely to do with the latest 
modification of SS.

**Comment by taylori** [comment] 2018-01-19 19:32
I think this is the issue with ss3.par vs ss.par that I flagged yesterday (https://github.com/cgrandin/hake-assessment/issues/312#issuecomment-358759721). I think we could comment out about 4 lines that contain "par.fn" in some form and just skip reading the par file. Alternatively, we could search for a file with extension ".par" and read that. There should only ever be a single file, with name either ss.par or ss3.par, but again, I don't think we actually need to read it.

**Comment by andrew-edwards** [comment] 2018-01-19 19:32
Aha:
```Browse[2]> par.fn
character(0)
```
so 
```readLines(par.fn)```

then tries to load in a file just called .r  (con is empty in the call to readLines().

**Comment by andrew-edwards** [comment] 2018-01-19 19:33
Thanks. Think I can fix it, have found
```  par.fn.ind <- grep("ss3.par", model.dir.listing)
```
which then defines par.fn.

**Comment by andrew-edwards** [comment] 2018-01-19 19:36
It gets used once to give the value of sigma_r:
https://github.com/cgrandin/hake-assessment/search?utf8=%E2%9C%93&q=%22model.par%22&type=

Presumably sigma_r can be obtained another way? Though I remember it being fiddly at the time.

**Comment by andrew-edwards** [comment] 2018-01-19 19:39
Don't worry, it's defined elsewhere. I can do it and then we won't need the .par
https://github.com/cgrandin/hake-assessment/search?utf8=%E2%9C%93&q=%22sigma_R_in%22&type=

**Comment by taylori** [comment] 2018-01-19 19:44
I think that one sigmaR reference is in a comment and wouldn't actually work if run. It should read base.model$pararameters instead of base.model$par.

**Comment by andrew-edwards** [comment] 2018-01-19 19:56
Have dealt with that, but still can't build. Looking at your r4ss commit
https://github.com/r4ss/r4ss/commit/a099714b881db4396301d07b417982d0d11d40c5#diff-b7dc229877721a6e0a55d14ba999b19f

do we have to do the same  our calc.mcmc()  ? i.e. switch SPB to SBB
See lines 246 onwards of
https://github.com/cgrandin/hake-assessment/blob/8006d0cb39dab9e3ea38a3964726b383cc726ba5/doc/r/r-functions/load-models.r
in which calc.mcmc is defined.

But it worked yesterday and your SPB to SBB change was in December!?!

**Comment by taylori** [comment] 2018-01-19 20:00
I think there were some lingering SPBs in the SS output that finally got sorted out in SSv3.30.10, so the new models uploaded yesterday would break the code. I think a case-sensitive find/replace of "SPB" to "SSB" within load-models.r (or even more broadly) should get it to work.

**Comment by andrew-edwards** [comment] 2018-01-19 20:02
When I change SPB to SSB here
```spb <- mcmc[,grep("SSB",names(mcmc))]/2e6
```
that line works. 

Yes, agree with what you just said. Should get through it.

**Comment by andrew-edwards** [comment] 2018-01-19 20:02
So what did the P in SPB stand for. SPawning Biomass?

**Comment by taylori** [comment] 2018-01-19 20:08
Yes, not the best abreviation.
I remember some discussion in previous years about what terminology to use
in the hake assessment but we seem to have settled on just using B (the
glossary shows commented-out definitions for SB and SSB.

**Comment by andrew-edwards** [comment] 2018-01-19 20:19
I always prefer just B for equations, as long as it's clearly defined.
```
build(T, T, T) 
```
seems to be working okay now (didn't get hung up on the loading in), though it's still running. knitr won't work yet until I correct other instances after lunch.

Presumably we wouldn't want to go back to the previous version of SS for the base model. I'm assuming we wouldn't.

**Comment by taylori** [comment] 2018-01-19 20:24
I agree, so unless something is obviously broken, you could merge your 2018.18 branch whenever you want.
And lunch is a good idea.

**Comment by andrew-edwards** [comment] 2018-01-19 20:29
Bleh. build(T, T, T) failed with
```
run.forecasts: Running forecasts for model located in ../../models/2018.18_temporary_base/mcmc...

Error in SS_readforecast(forecast.file, Nfleets = 1, Nareas = 1, nseas = 1,  : 
  Error in read of input forecast catch.
Number of values should be a multiple of 4.
Values:
2
```
Will investigate after lunch.

**Comment by taylori** [comment] 2018-01-19 20:31
Dangit, I saw this and found that I had an error in r4ss but failed to commit it. I will track it down and get it into the trunk. Sorry!

**Comment by andrew-edwards** [comment] 2018-01-19 20:58
Excellent. Much easier than me doing it!

**Comment by taylori** [comment] 2018-01-19 21:02
Took me a surprisingly long time to figure it out, even looking at my full R history from yesterday. I had tried to debug SS_readforecast, but after loading it, the error went away so I forgot about it. Turns out the issue was in a copy of that function in our utilities.r which hadn't been updated. I just commented it out, such that the r4ss version will be used instead, and `build(T,F,F)`  (trying to focus on forecast step) got it working again. See my most recent commit.

Unfortunately, after running the forecasts, it produced this error. I need some food before tacking that one.
```
getting files from ../../models/2018.18_temporary_base/mcmc/forecasts/forecast-year-2017/01-0 
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1001 did not have 220 elements
```

**Comment by taylori** [comment] 2018-01-19 21:08
Debugging while eating lunch:
Looks like that error is in SSgetMCMC, but I cancelled the MCMC-related step to save time, so trying again with build(T,T,T) instead of built(T,F,F) and hopefully the issue will go away.

**Comment by andrew-edwards** [comment] 2018-01-19 21:47
Did you push (regarding your commit two comments ago)?

**Comment by taylori** [comment] 2018-01-19 21:52
Sorry, forgot to push. Did so just now.
Issue with SSgetMCMC was related to -mceval command not working right due to clean.bat deleting .psv file (see issue #159). I'm re-running the mcmc for model 2018.18 and will upload all output shortly (without running clean.bat), including the .psv file which is maybe the only one missing that's important.

Running using
ss3 -mcmc 12000 -mcsave 10 -mcseed 36519

**Comment by andrew-edwards** [comment] 2018-01-19 21:55
Thanks. I'm not too bothered about clean.bat. I'll upload when you're done.

**Comment by taylori** [comment] 2018-01-19 22:17
OK, just replaced all files in /2018.18_temporary_base/mcmc/ on Google Drive.
build function seems to now be working, but taking longer than before because -mceval steps are doing actual calculations, rather than spitting error and moving on.

**Comment by andrew-edwards** [comment] 2018-01-19 22:45
Yes, looks like it's taking longer. So why is it now doing calculations when it didn't (need to?) before?

**Comment by taylori** [comment] 2018-01-19 22:48
I think that before it was just failing every time it tried a new mceval (e.g. for a new catch level in the forecast). Therfore, the results would have been identical for all of the mcmc samples and the plots and uncertainty intervals would have revealed something wrong if we'd gotten to the stage of building the document with the new 2018.18 model

**Comment by andrew-edwards** [comment] 2018-01-19 22:59
Just stopped:
```
create.rdata.file: RData file found in ../../models/00_55_2016base. Deleting...

Error in SS_readdat_3.30(file = file, verbose = verbose, echoall = echoall,  : 
  Error - There was no EOF marker (999) in the data file.
```

**Comment by andrew-edwards** [comment] 2018-01-19 23:03
Your last comment could explain why results are:
![image](https://user-images.githubusercontent.com/6977190/35175711-d10378d4-fd29-11e7-94c4-0d9e66c5dfe6.png)

I just thought that was because we hadn't specified different catch levels yet (I haven't checked). Okay for now to get such results as just want everything building. Like it was yesterday :(  ;)

**Comment by taylori** [comment] 2018-01-19 23:03
Just saw this too.
Seems related to 
```
create.rdata.file: No RData file found in ../../models/00_55_2016base. Creating one now.
```
where it thinks that last years model was in version 3.30, not 3.24. I'm trying to navigate mode-setup.r to figure out how to tell it otherwise.

**Comment by andrew-edwards** [comment] 2018-01-19 23:07
Line 45 sets the default:
```
ss.version <- "3.24"
```
Line 384 switches the SS version for the base model. 
So is it now trying to run more stuff on the 00_55_2016base than it was yesterday?

**Comment by taylori** [comment] 2018-01-19 23:20
In the calc.mcmc function in load-models.r, it's returning nothing at 
```
  sinit.post <- ssb[,names(ssb) == "SSB_Initial"]
```
due to the SPB vs SSB issue. Unfortunately in my efforts to keep the SS_output function using the updated terminology for both 3.24 and 3.30 models, I didn't think to extend that to reading of MCMC outputs.

We could either add some switches to use either SSB or SPB depending on ss.version. Or we could use regular expressions to look for S*B. But I'm not good with regular expressions.

**Comment by andrew-edwards** [comment] 2018-01-19 23:25
Or should we just give up trying to switch between two versions of SS, and just make some dummy retros and sensitivities to get it building?
Seems like we're expending energy on something that will not matter for the assessment anyway. 
Though, I guess we need the 3.24 version working for last year's base model.

Could maybe revert to yesterday's GitHub files to rebuild the .RData file for 00_55_2016base (and use yesterday's 2018.18 - I kept the .zip file from Google). Then revert back to today's with today's 2018.18 to build the .RData for that. Hmmm.... not ideal or very repeatable! [Leaving that idea here as a last resort if it's just me next week!].

Can try the switches. Shoudn't be too bad as they are already defined for each version. Depends how many there would be.

**Comment by andrew-edwards** [comment] 2018-01-19 23:28
We should just rename the output appropriately (once it's loaded in) to conform to SS3.30 style.
Something like we did the other day in 8006d0c  (which took us a long time to figure out).

**Comment by taylori** [comment] 2018-01-19 23:29
On second thought, I think it would work to just replace any SPB in the column names of the MCMC output with SSB, regardless of whether they are present.

Yes, just saw your message that's the same. Do you want to attempt this or should I?

Also, to get that stage, I had to make commit 4d5829e28b00726678a8f00568ce727b1bf331b9

**Comment by taylori** [comment] 2018-01-19 23:31
I think we could do
```
names(model$mcmc) <- gsub(pattern="SPB", replacement="SSB", names(model$mcmc))
```

**Comment by andrew-edwards** [comment] 2018-01-19 23:36
I'm not too familiar with gsub but that sounds like what we need (shorter than our similar commit 800630c). 
Looks like SSgetMCMC() only gets called in load-models.r . It appears elsewhere but only in comments I think. Can't chage SSgetMCMC() as it's in r4ss.
Yes, you should attempt the change.

**Comment by andrew-edwards** [comment] 2018-01-19 23:40
Your gsub command seems to work on a simple example. If you push the commit I'll re-run also.

**Comment by taylori** [comment] 2018-01-19 23:40
Just committed that change to load-models.r that got past that point and build() was able to complete.
Now in build.doc() there's an issue with catch.limit.quantiles related to end.yr = 2017 instead of 2018.

**Comment by andrew-edwards** [comment] 2018-01-19 23:41
How did build() work so quickly? Oh, you're not doing build(T,T,T).

**Comment by andrew-edwards** [comment] 2018-01-19 23:41
We changed assess.yr to be 2017 not 2018 to get it running. But it worked yesterday - just might not give sensible results.

**Comment by andrew-edwards** [comment] 2018-01-19 23:44
I get same error [build() worked].  
Think that's easier to fix. 
I'm going to do build(T, T, T) again to get everything up to date.

**Comment by taylori** [comment] 2018-01-19 23:45
Yes, exactly. I was doing build() to go fast. Maybe that's the problem.
In custom-knitr-variables.r, the calculation
```
catch.limit.quantiles <- f(as.numeric(quantile(base.model$mcmc[[paste0("ForeCatch_", end.yr)]],
                                               probs=c(0.025, 0.5, 0.975))))
```
is looking for "ForeCatch_2017" which doesn't exist for the 2018.18 model which has the forecast start in 2018.

**Comment by andrew-edwards** [comment] 2018-01-19 23:47
So we changed assess.yr to keep the old sens/bridge ones working. But it should still work.

**Comment by andrew-edwards** [comment] 2018-01-19 23:51
Am rerunning build(T,T,T). 
Good spot on  4d5829e

**Comment by andrew-edwards** [comment] 2018-01-19 23:55
Slightly unintuitive that my model.2018.18 branch is merged into your master branch. I guess now that we're both caught up you can't see any differences on the Network Graphs.

**Comment by taylori** [comment] 2018-01-19 23:59
Yes, last time I tried to merge a branch into a branch I got confused about
it, so instead took the easy path. I think as long as we both remember
where things are, we're OK.

**Comment by andrew-edwards** [comment] 2018-01-20 00:06
Indeed. I'm not merging until it all works again (so can easily revert if necessary). build is still running...

**Comment by taylori** [comment] 2018-01-20 01:00
build(T,T,T) just finished for me, but sadly didn't remove error in build.doc()
```
Quitting from lines 2-67 (./one-page-summary/one-page-summary.rnw) 
Quitting from lines NA-67 (./one-page-summary/one-page-summary.rnw) 
Error in eval(parse_only(code[i]), envir = envir) : 
  object 'catch.limit.quantiles' not found
```

I think that end.yr = 2017 was fine for the models used before because they were really just the 2017 model converted to 3.30. Now that we're trying to switch to a base model that includes 2017 data, it may be necessary to switch to end.yr = 2018.

Producing new sensitivities for the 2018.18 model to help that switch might be needed but I think any contribution from me on that will have to wait until another day.

**Comment by andrew-edwards** [comment] 2018-01-20 01:08
But the build worked which is great.
I think the other day we had the error you had and changing assess.yr change fixed that. 
I thought it kind of just ignored the 2017 data, but maybe not.  I'm bit confused as to exactly why it doesn't work now, but, yes, rather than trying to figure it out, can try assess.yr to be 2018. Maybe we also changed it because we're using last year's sensitivities still (as placeholders). 

But having the build work is good. I think it won't work with last year's sensitivities, so maybe (if it's just me next week) I'll use your bridging analyses you uploaded and do a simple sens to get it building with assessment year of 2018. 
Yes, that won't happen now either, but I'm more comfortable now that you got the build working. knitr stuff is a bit easier to trace.

**Comment by andrew-edwards** [comment] 2018-01-20 01:31
So, to summarise:

- build(T, T, T) now works. knitr doesn't build but that could be because years are out of sync (though I'm suspicious because the years out of sync are for last year's sens and bridging). 

- I get the same error as Ian's (two comments up), which is good.

- Ian's master branch merged my model2018.18 branch. I have my master and model2018.18.

- My master branch did work this morning (for the 2018.18.temporary_base that was on Google Drive *before* today - Ian changed the Google Drive this morning).

- I can revert to that if necessary just to get on with some editing of text, but would rather merge my model2018.18 branch back in to avoid conflicts. 

Chat Monday at 11:15. Don't think I'll get any further with this even if I tried.

**Comment by taylori** [comment] 2018-01-20 01:36
Good summary. I agree on all points except that since I wasn't keeping up yesterday, I'm not sure what worked and what didn't and why it worked if it did work.

**Comment by andrew-edwards** [comment] 2018-01-20 01:42
Just remembered that we had to do 
```
delete-rdata-files()
```
I just did it thought it's a bit drastic. Then build() can be done to rebuild the .Rdata files. Shouldn't take as long as build(T, T, T), but still a short while.

**Comment by andrew-edwards** [comment] 2018-01-20 01:56
Well, that didn't work. So I'm done. Need to look at this again fresh (and remind myself exactly what order things need to be done in).

**Comment by cgrandin** [comment] 2018-01-22 18:37
Hi guys, sorry for being out of the loop so long here. I will talk to you today and will be in the office tomorrow. The root cause of most of these bugs is having two different model versions and all the special case code needed to deal with that. I'm sure I can get everything working once I get back up to speed.

**Comment by cgrandin** [comment] 2018-01-23 17:21
In the SS_output function, line 972-974 needs to be changed from this:

` wtatage <- read.table(wtfile, header = FALSE, comment.char = "", `
                `skip = grep("yr seas gender", wtatagelines), `
                `stringsAsFactors = FALSE)`

to this:

` wtatage <- read.table(wtfile, header = FALSE, comment.char = "", `
                `skip = grep("Yr Seas Sex", wtatagelines), `
                `stringsAsFactors = FALSE)`

As a hack, I just added a new source file which is a copy of the SS_output function.

**Comment by cgrandin** [comment] 2018-01-23 18:26
In the function `run.forecasts`, the command `ss3 -mceval` is called for each forecast. With version 3.10.10 this command is appending an extra header and row of zeroes to the bottom of the `posteriors.sso` file. This is what causes the `fetch.forecasts` function to fail later when it tries to read it.

**Comment by taylori** [comment] 2018-01-23 18:50
**Regarding `SS_output`**
The change for the wtatage reading was already made--see current code at https://github.com/r4ss/r4ss/blob/master/R/SS_output.R#L1091. Perhaps you're using a specific snapshot from last year rather than the latest from GitHub?

**Regarding `run.forecasts`**
I noticed the appending the extra lines but thought it was because I was re-running in existing file. I will report the bug in SS that the files are not getting deleted properly, but should be able to work around it but deleting `posteriors.sso`, `derived_posteriors.sso` and `posterior_vectors.sso` before each `-mceval` call.

**Comment by cgrandin** [comment] 2018-01-23 19:12
Thanks, I re-installed r4ss and then reverted the changes I had made so it seems to be working now.

**Comment by cgrandin** [comment] 2018-01-26 18:30
We have this all working, ss.version is now 3.30 and everything loads and document builds. The forecasts also appear to be working correctly so I'll close this issue.

**Closed by cgrandin** 2018-01-26 18:30 UTC

**Comment by taylori** [comment] 2018-01-26 18:39
This is a big milestone. Nice work getting it done.
If I had any idea of the risk of government shutdown I would not have encouraged the switch to 3.30 in general (or 3.30.10 from 3.30.08).

**Comment by andrew-edwards** [comment] 2018-01-26 19:23
These trivial issues are just easy to polish off....
