### ISSUE TITLE
all.r saves the image when you reload models but does not when you don't

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#71] opened 2016-02-07 22:10 UTC
If you answer "n" to all the questions, it does not save an image. But, if you changed a function, you will need to save that image.

**Comment by cgrandin** [comment] 2016-02-07 22:51
That's by design - when working on R source code and debugging, you want to source("all.r") all the time, but the save image takes a long time so when happy with the changes to r code, you can save the image manually.

**Comment by cgrandin** [comment] 2016-02-07 23:18
A little trick... If you change any r code at all, in any of the files, source all.r and you can just quickly press enter four times (same as typing ''n") and you can test your changes. No need to source the file you're working on

**Comment by allan-hicks** [comment] 2016-02-08 01:15
I think I understand.  I ran into some issues when making changes to code,
though. When I forgot to save the image to .Rdata, it must reload that and
replace the changes I had made when running knitr?  So, I always save the
image (and almost always delete knit-cache) just to be safe.

**Comment by cgrandin** [comment] 2016-02-08 01:17
Yes, if I'm messing about with code or not sure what has been done after a merge, I do the same, source and save image, delete cache, and rebuild. Can we close this?

**Comment by allan-hicks** [comment] 2016-02-08 01:18
yep.

**Closed** 2016-02-08 01:21 UTC
