### ISSUE TITLE
beamer - data section

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#413] opened 2018-02-20 22:51 UTC
I can't figure out why the function:
make.catches.plot(catches, leg.y.loc = 550, leg.cex = 0.7), works just fine in the document build (i.e., it includes the survey abundance estimates, but doesn't in the presentation build.  It works just fine in the R when run standalone.  Thus, I'm guessing its a setting issue within beamer for the build of that particular figure.  I've fooled around with a bunch of stuff to no prevail.  Any suggestions?  Alternatively, I could just create an eps file of the figure and import directly.

**Comment by aaronmberger** [comment] 2018-02-20 22:55
Opps, I meant the data function:

make.data.overview.plot(base.model)

**Comment by taylori** [comment] 2018-02-20 23:00
That figure built just fine for me when I merged your code this morning and ran buildtex.bat on each of presentations. I would try deleting knitr-cache (or running freshtex.bat) to see if those get it working.

![image](https://user-images.githubusercontent.com/4992918/36453909-ae0b71c2-164e-11e8-81b4-fb33933357a4.png)

**Comment by aaronmberger** [comment] 2018-02-21 16:33
Yeah, I've tried all sorts of things including running freshtex.bat and then buildtex.bat.  Everything else looks fine, it's just this one figure... interesting.  I'm not going to linger on it now, as it is working for you.  Here is what mine looks like (with title?):
![image](https://user-images.githubusercontent.com/7946234/36492191-696737ca-16e1-11e8-91d6-63a5df0044a6.png)

**Comment by andrew-edwards** [comment] 2018-02-21 21:30
Ian's figure has a main title but yours doesn't - I had this happen a while back (I think I noticed it when I was comparing early versions of our .pdf's). I have a feeling you may just have to update r4ss from GitHub. I've had a look through Issues but can't pin it down.

**Comment by andrew-edwards** [comment] 2018-02-21 21:30
I forget - can we easily tell which version of a GitHub-installed package we have?

**Comment by taylori** [comment] 2018-02-21 21:39
The most complete information is available via `packageDescription()` (as opposed to `packageVersion()` which just gives version number). I've pasted the whole business below, but the key difference between the trunk and the 'development' branch that we've been using is near the bottom: `RemoteRef: development`.  Both trunk and branch should shown version 1.30.1 with Feb 2 date.

```
> packageDescription('r4ss')
Package: r4ss
Type: Package
Title: R Code for Stock Synthesis
Version: 1.30.1
Date: 2018-02-02
Author: Ian G. Taylor, Ian J. Stewart, Allan C. Hicks, Tommy M.
        Garrison, Andre E. Punt, John R. Wallace, Chantel R. Wetzel,
        James T. Thorson, Yukio Takeuchi, Kotaro Ono, Cole C. Monnahan,
        Christine C. Stawitz, Z. Teresa A'mar, Athol R. Whitten, Kelli
        F. Johnson, Robbie L. Emmet, Sean C. Anderson, Gwladys I.
        Lambert, Megan M. Stachura, Andrew B. Cooper, Andi Stephens,
        and Neil Klaer
Maintainer: Ian G. Taylor <Ian.Taylor@noaa.gov>
Depends: R (>= 2.10.0)
Imports: coda, corpcor, gdata, gplots, gtools, pso, truncnorm
Suggests: maps, testthat, knitr, rmarkdown
Description: A collection of R functions for use with Stock Synthesis,
        a fisheries stock assessment modeling platform written in ADMB
        by Dr. Richard D.  Methot at the NOAA Northwest Fisheries
        Science Center. The functions include tools for summarizing and
        plotting results, manipulating files, visualizing model
        parameterizations, and various other common stock assessment
        tasks.
License: GPL-3
LazyLoad: yes
URL: https://github.com/r4ss
RoxygenNote: 6.0.1
VignetteBuilder: knitr
Built: R 3.4.1; ; 2018-02-21 21:36:30 UTC; windows
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: r4ss
RemoteUsername: r4ss
RemoteRef: development
RemoteSha: 49dbcbafee720e5a69c816536901867f57e3e8c4
GithubRepo: r4ss
GithubUsername: r4ss
GithubRef: development
GithubSHA1: 49dbcbafee720e5a69c816536901867f57e3e8c4
```

**Comment by taylori** [comment] 2018-02-21 21:54
What's strange is that Aaron is getting the correct plot outside of the beamer presentation, implying that it's not necessarily a version issue. I just uploaded the .eps from knitr-cache to  /beamer/SRG/Data/data_overview_map-1_backup.eps in commit 77a93da so that if the source of the problem isn't found, you can just point the presentation to this file.

**Comment by aaronmberger** [comment] 2018-02-21 21:57
Thanks Ian, I'm going to use your uploaded eps for my build for now.

**Comment by cgrandin** [comment] 2018-02-21 22:05
Weird.. I checked and mine builds fine as well, even with Aaron's changes merged in.

**Comment by kellijohnson** [comment] 2018-02-21 22:08
Has anyone checked if the lack of build is b/c latex packages need to be updated or latex version?

**Comment by aaronmberger** [comment] 2018-02-21 22:22
Thanks Kelli, that could be as I can't recall the last time I updated those (usually I do at the beginning of hake assessment season but I don't remember now, easy enough to check)

**Closed** 2018-02-21 22:48 UTC
