### ISSUE TITLE
Feb 1 - document build working with new 24 million sample MCMC

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#352] opened 2018-02-01 22:54 UTC
I re-ran everything and it's building properly with the new variable number of posterior samples. 
`build(T,T,T)`
It took a long time, over an hour for it to run though.

**Comment by taylori** [comment] 2018-02-01 23:56
Thanks for getting it working again.

My `build(T,T,T)` and `build.doc()` just finished. Time use for `build()` seems to have been approximately as follows:
- 30 minutes for extra-mcmc (about 1 second each for the 2000 runs without estimation to get a Report.sso from each MCMC sample), 
- 15 minutes each for retrospectives 
- 15 minutes for forecasts
- 15 minutes for extra-mcmc for 00_55_2016base (listed as last.yr.base.model, but should be updated to be "45_BasePreSRG_v4")
- 15 minutes on extra-mcmc for 59_Sen45_phi003 (needed for selectivity plots in Figs 48-50 for comparison to base model in last year's assessment)

In general, the results look reasonable (based on the majority of the plots that are working and updated for this new base model). However, the MCMC diagnostics look a little bit worse than last year:
![image](https://user-images.githubusercontent.com/4992918/35709465-7a9e69d4-0767-11e8-889d-13e44852b108.png)

Even though the chain is twice as long, we're thinning at the same rate as before to get 2000 samples instead of 999, so I would have expected things like the autocorrelation and lower range of effective sample size to remain the same. And our burn-in is slightly longer (400 x 10,000 = 4 million vs. 2.1 million before). It may be the new Dirichlet-Multinomial parameters that are causing the slightly worse performance, so I will try adding them to Fig 19 in case that provides some clues. We could also expand the caption for Fig 18 to list any parameters which fails the Heidelberger and Welch statistic.

**Comment by aaronmberger** [comment] 2018-02-02 00:12
Yeah, I wonder if the thinning rate needs to increase to reduce the autocorrelation

**Comment by taylori** [comment] 2018-02-02 00:29
The command below suggests that its the "Early_InitAge_9" parameter (recruitment in 1957 contributing to age 9 in the initial age structure) which fails the Heidelberger and Welch stationarity test, either with or without sub-sampling the rows to reduce to 1000 samples instead of 2000 using `seq(2,2000,2)`. But I'm not seeing anything out of the ordinary with that parameter.

```
> hd <- heidel.diag(base.model$mcmc[seq(2,2000,2), names(base.model$mcmc) %in% base.model$parameters$Label])
> hd
                                                 
                   Stationarity start     p-value
                   test         iteration        
NatM_p_1_Fem_GP_1  passed         1       0.23871
SR_BH_steep        passed         1       0.14462
Early_InitAge_20   passed         1       0.11004
Early_InitAge_19   passed         1       0.25107
Early_InitAge_18   passed         1       0.80111
Early_InitAge_17   passed         1       0.30445
Early_InitAge_16   passed         1       0.73099
Early_InitAge_15   passed         1       0.89804
Early_InitAge_14   passed         1       0.36156
Early_InitAge_13   passed         1       0.53285
Early_InitAge_12   passed         1       0.39736
Early_InitAge_11   passed         1       0.10397
Early_InitAge_10   passed         1       0.70156
Early_InitAge_9    failed        NA       0.00676
Early_InitAge_8    passed         1       0.81515
```

**Comment by taylori** [comment] 2018-02-02 02:46
Sorry, somewhat long message below:

**More info on the MCMC convergence**
I'm rusty with the coda package and the use of mcmc.out (as copied from r4ss to utlities.r), but here's a bit more info. First, the Heidelberger and Welch command in the previous comment should have been
```
hd <- heidel.diag(base.model$mcmc[seq(2,2000,2), 3:227])
```
since the `%in%` fails to account for R renaming columns with "()" in the header.
Fixing that and looking more closely showed that both `Early_InitAge_9` and `Main_RecrDev_1976` failed the stationarity test. However, I think the bigger culprit is the Dirichlet-Multinomial parameter for the survey likelihood (`ln(EffN_mult)_2` or `ln.EffN_mult._2` as read by R). This parameter has high autocorrelation, even after thinning from 2000 to 1000 (e.g. keep every 20,000 samples out of the 24 million)
```
> acf.out = acf(base.model$mcmc$ln.EffN_mult._2[seq(2,2000,2)], lag.max=5)
> acf.out

Autocorrelations of series ‘base.model$mcmc$ln.EffN_mult._2[seq(2, 2000, 2)]’, by lag

     0      1      2      3      4      5 
 1.000  0.257  0.101  0.009 -0.044 -0.024 
```
In hindsight, I should have thought more about what it meant that "median weights given to the fishery and survey age comps are 0.36 and 0.99, respectively" as I commented yesterday: https://github.com/cgrandin/hake-assessment/issues/315#issuecomment-362117401.

As described in the new "Age composition likelihood" section of data.rnw, the sample size multiplier is equivalent to theta / (1+theta) where the estimated parameter is log(theta). Jim Thorson previously suggested bounds of -5 to 20 on the log(theta) parameters and that if any of them was hitting the upper bound, then it could be fixed at that bound, and our MLE value for the log(theta) is 2.427, corresponding to a weight of theta / (1+theta) = which seemed fine. But that didn't account for potential impact on MCMC convergence.

The median value in the MCMC of the log(theta) for the survey is 9.1: 
```
> summary(base.model$mcmc$ln.EffN_mult._2)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.5546  4.2593  9.1030  9.5654 14.4342 19.9850 
```
and when these are transformed into the weights as theta / (1+theta), most of them are really close to 1.0.
```
> theta2 <- exp(base.model$mcmc$ln.EffN_mult._2)
> summary(theta2 / (1+theta2))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.6352  0.9861  0.9999  0.9766  1.0000  1.0000 
```
Once the weight gets close to 1, further changes in the log(theta) parameter have almost zero impact on the model results, so the MCMC can wander aimlessly with little information about where to go in that dimension. I think that the Early_InitAge_9 and Main_RecrDev_1976 are influenced by the relative weight given to the fishery vs. the survey age comps, so whenever log(theta) wanders down to a lower value, those parameters respond, but that's occurring in a way that leads to higher autocorrelation and failnig the stationarity test. Here's a trace of the log(theta) and theta / (1+theta) weight:
![image](https://user-images.githubusercontent.com/4992918/35712906-7258bd4e-0779-11e8-8dcd-73649025f1be.png)

**What to do about it**
I see a few options, although there are surely others.

1. Not worry about it and move on, since the poorly converged parameters have little impact on the quantities of interest like current stock status or forecast catch
2. Fix the log(theta) at the MLE or some larger value that results in effectively giving survey input sample sizes close to full weight, which would probably make MCMC work better for other parameters
3. Go back to McAllister-Ianelli tuning method and make the D-M option be a sensitivity instead
4. Try the alternative selectivity in the hope that the potential benefit to the MCMC convergence for the selectivity parameters will allow the survey's log(theta) parameter time to converge better (probably the least sure to work compared to the above)

I'm going to start 12 million MCMC samples for a set of models corresponding to options 2-4 on the list (should be done around noon tomorrow) so that if we're on the fence about what to do we can have more information tomorrow.

**Comment by aaronmberger** [comment] 2018-02-02 15:23
I guess I'm not too worried about that init parameter failing, especially when the MLE and median of the posterior from MCMC results in similar derived quantities for management (which is not surprising given it's an init recruitment parameter for age 9 at the start of the model 40 years back).  I'm a bit more concerned about the level autocorrelation that remains (note that past assessments the autocorrelation plot was mostly normal looking, centered around 0.  The fact that this one is skewed to the right suggests that we may not be thinning enough for this model's chain.  I'm quite curious if Ian's new run with the new t.v. takes care of some of this. 

Also, since we now have more than one chain run (two different lengths/samples, but same thin rate in this case), it might would be worth running the Gelman-Rubin diagnostic and gelman.plot as in:

combinedchains = mcmc.list(chain, chain2)
plot(combinedchains)
gelman.diag(combinedchains)
gelman.plot(combinedchains)

The "Gelman-Rubin measures whether there is a significant difference between the variance within several chains and the variance between several chains by a value that is called “scale reduction factors”. The gelman.diag gives you the scale reduction factors for each parameter. A factor of 1 means that between variance and within chain variance are equal, larger values mean that there is still a notable difference between chains. Often, it is said that everything below 1.1 or so is OK, but note that this is more a rule of thumb. The gelman,plot shows you the development of the scale-reduction over time (chain steps), which is useful to see whether a low chain reduction is also stable (sometimes, the factors go down and then up again, as you will see). "

**Comment by aaronmberger** [comment] 2018-02-02 15:27
If we decide to go with the current model, we should try to fix the theta parameter at the MLE for the MCMC run and compare the results to current.  Let's work through this shortly after noon today once we have the info that Ian is gathering (great detective work btw Ian!).  Do we need a call or is github okay?

**Comment by aaronmberger** [comment] 2018-02-02 16:54
Did the acceptance rate change between the 12 and 24 million, likely not given the 'sampling scheme' was effectively the same.  What was the acceptance rate (~0.25)?  Sometimes the acceptance rate can also indicate autocorrelation (e.g., rates < 0.20).  Still thinking that dealing with the theta parameter will fix this....

**Comment by aaronmberger** [comment] 2018-02-02 17:19
The Gelman-Rubin approach requires to separate chains (i.e., different starting values and/or random seeds) so we don't have this info currently.  Put this on hold until later today after further mcmc results are complete.

**Comment by taylori** [comment] 2018-02-02 17:50
Thanks for all the comments, Aaron. Unfortunately, I think we don't have a good multi-chain comparison because all the runs used the same seed and thinning rate. That is, the 12 million chain used the old settings:
```
ss3 -mcmc 12000000 -mcsave 10000 -mcseed 36519
```
and the 24 million used the new settings
```
ss3 -mcmc 24000000 -mcsave 10000 -mcseed 36519
```
But you make a good point. It would be easy to run a new chain with a different seed to either use multi-chain statistics, or to combine samples from multiple chains to get 2000 samples with a larger thinning ratio.

In my note about options for what to do, I should have noted that a longer chain was an additional option, but I think that 36 hours for the 24 million is already pushing the limit of what's practical.

**Comment by taylori** [comment] 2018-02-02 20:11
Update on MCMC and choosing a base model. 
Short version: My suggestion is to fix the log(theta) parameter at the MLE value for MCMC.

I started chains of length 24 million yesterday evening knowing that I could copy the files mid-stream and run -mceval to see their progress at an intermediate stage. As of an hour ago, they had reached about 10 million samples, or 1000 after thinning. Using a burn-in of 200 gave me 800 samples to look at.

A comparison of the model results of 2018.40_base_model and the 3 alternatives is in the file SSplotComparisons_02-Feb-2018_11.00.pdf I just uploaded to the main "Hake JTC 2018" folder on Google Drive. First off, the MCMC results for all models are very similar overall. The notable differences are that the McAllister-Ianelli model (2018.41 in green) differs a bit in the early period due to slightly different weights on age comps, and the semi-parametric selectivity model (2018.43 in red) has a much higher estimate of 2016 recruitment.

I also just called Jim Thorson to have a conversation with him about what to do about a Dirichlet-Multinomial that doesn't behave well in the MCMC and that helped solidify my suggestion that the best option would be to fix the parameter at the MLE value for MCMC (option 2 among those listed yesterday and repeated below). Here is a bit more explanation of my thinking about each option.

1. _Not worry about it and move on, since the poorly converged parameters have little impact on the quantities of interest like current stock status or forecast catch_ We could use the fixed-value MCMC as evidence that the poor convergence doesn't matter, but I think that for fishery stakeholders and all others who haven't studied Bayesian statistics, saying that our base model had not fully converged would just sound bad. And Trevor who HAS studied Bayesian stats might give us an even harder time.
2. _Fix the log(theta) at the MLE or some larger value that results in effectively giving survey input sample sizes close to full weight, which would probably make MCMC work better for other parameters_ We could use the results of option 1 as a sensitivity to show that fixing log(theta) really didn't change the central tendency or reduce the uncertainty in the model results. For purposes of the sensitivity analyses done in MLE, we could still estimate the parameter, but that's a separate decision.
3. _Go back to McAllister-Ianelli tuning method and make the D-M option be a sensitivity instead_ This would feel like a small step backward in the sense that the weights applied to age comps from both fleets would be fixed, as opposed to still estimating the Dirichlet-Multinomial parameter for the fishery, which is the fleet that has the longer time series and also the most uncertain with regard to how much to trust the age data.
4. _Try the alternative selectivity in the hope that the potential benefit to the MCMC convergence for the selectivity parameters will allow the survey's log(theta) parameter time to converge better (probably the least sure to work compared to the above)_ The alternative selectivity did not change the problem of autocorrelation in the Dirichlet-Multinomial log(theta) parameter. Still interested in this setup for the future, but not a solution to the immediate problem.

**Comment by aaronmberger** [comment] 2018-02-02 20:14
Just stepping out for lunch but will provide feedback soon

**Comment by taylori** [comment] 2018-02-02 20:30
Getting some lunch now myself. Here are some statistics for the 2018.42_fix_survey_log-theta model for comparison to those posted yesterday for 2018.40_base_model at https://github.com/cgrandin/hake-assessment/issues/352#issuecomment-362441400. This is with same thinning but shorter chain so max sample size is about 800 instead of 2000:

![image](https://user-images.githubusercontent.com/4992918/35753422-92af6890-0814-11e8-93fc-e1bbf867f6fd.png)

**Comment by aaronmberger** [comment] 2018-02-02 20:34
Well those look quite good at first glance

**Comment by cgrandin** [comment] 2018-02-02 21:09
Hi Ian,

Thanks for your detailed work on this. I've been busy with some other things here so am coming in fairly late, but I agree with your suggestion to fix log(theta) at the MLE value. Showing that this doesn't have much impact by allowing it to be estimated in a sensitivity will help. It seems with 800 samples, that plot is probably close to what will come out once we have all of them. It's pretty clear that the both initial biomass and the time series don't change much looking at the 4 alternatives.

**Comment by aaronmberger** [comment] 2018-02-02 22:15
My vote is for option 2, where we fix it at the MLE during MCMC.  I think that is a defensible way forward.

Weights were not previously re-tuned in all previous assessment MCMCs anyway so in a sense this approach is not all that different than what was done in the past - just an improved way of getting there.  And we can show that any additional parameter 'interactions' as a result of estimating theta during MCMC did not increase the overall uncertainty (it was 'absorbed' within the overall variation through interactions of other uncertain parameters - if that makes sense outside of my own mind).

As far as MLE sensitivities - I think we do not fix it.  That's part of the advantage of moving to the DM approach.  It probably won't make much of a difference anyway as most of our sensitivities deal with parameter uncertainty - the addition of the age-1 index sensitivity is perhaps the one where's there might be a difference (?).

**Comment by taylori** [comment] 2018-02-02 22:29
This works for me. In that case, I think we can continue to keep 2018.40_base_model as the base model, and just replace the mcmc folder with the results of the ongoing mcmc for model 2018.42_fix_survey_log-theta once it has finished the full 24-million. The point estimates for those two models are identical. Then we can add a note saying something like 

> The log(theta) parameter was found have high autocorrelation in MCMC sampling, due to a large set of potential values all having similar likelihood (associated with a weight of almost 100% of the input sample size). Therefore, this parameter was fixed at it's MLE value for purposes of MCMC sampling. The parameter remained freely estimated in sensitivity and retrospective analyses.

The MCMC should be finished sometime in the night tonight, but we could start on sensitivities from model 2018.40 if we want. Or just enjoy the weekend and start dealing with these things on Monday. Whatever you all want.

**Comment by cgrandin** [comment] 2018-02-02 22:33
Sounds like a good plan.

I've got some things to do this weekend (I haven't seen my kids for a week), but will be ready to go for Monday and all next week.

**Comment by aaronmberger** [comment] 2018-02-02 22:37
I will make an attempt to run all sensitivities later today and/or over the weekend if need be.  I've had several things come ups this week that have taken me away so I would like to volunteer for this to catch up on my contribution time.  Plus, I'm interested to see how things go!

**Comment by taylori** [comment] 2018-02-03 20:10
Aaron, thanks for doing all those sensitivities.

I just uploaded the new mcmc with fixed log(theta) parameter. It is in both `2018.42_fix_survey_log-theta\mcmc` and `2018.40_base_model\mcmc` since the only difference between these models with fixing that parameter at the MLE. The old mcmc runs with the parameter estimated are in `2018.40_base_model\old_mcmc` for lack of a better place to put them, in case we want to include more detail about the convergence issues posted to this issue above.

However, it looks like there's a bit more work to do on issue #353 to get the extra-mcmc working, which I'll tackle next, so no need to do `build(T,T,T)` yet.

**Comment by aaronmberger** [comment] 2018-02-03 20:15
Okay, so are we using the 2018.42 model mcmc results as our 2018.40  mcmc, so just need to make sure we  each have the correct mcmc folder associated with our base model folder structure.  I just copied it over on my local models folder. 

I'm going to set of another 24 mil mcmc on 2018.42 that is exactly the same as the one you did Ian, but with a different random seed, just so we can explore any multi-chain convergence diagnostics if we feel like it.

**Comment by taylori** [comment] 2018-02-04 01:24
Yes, we could likely close this, but maybe should leave open until Andy and Chris have a chance to move the `2018.40_base_model/mcmc_24mil-grandin` (or whatever it was called), into `old_mcmc` or some other location and download
`2018.42_fix_survey_log-theta/mcmc`
and copy that into 
`2018.40_base_model/mcmc`

**Comment by taylori** [comment] 2018-02-04 01:27
As a way to check that we're all seeing the same results, my one-page summary says "2018 female spawning biomass is 1.357 million t", which matches this calculation
```
> median(base.model$mcmc$SSB_2018)/2
[1] 1356528
```

**Comment by andrew-edwards** [comment] 2018-02-05 02:02
Just downloaded everything, merged, built, knitr-ed and it all works. Haven't thought about anything yet, just wanted to get the build done at home so I can get going tomorrow. Thanks for the hard work while I was away.

**Comment by andrew-edwards** [comment] 2018-02-05 18:57
Thanks guys for all the work on this - yes, the fixing theta at the MLE sounds sensible.

Yes - I get the exact same median biomass, so (presumably) have the right directories. (I didn't download anything last week from the Google Drive, did it all at home yesterday - just kept an eye on Issues, which is presumably why I'm good, yes?).
Chris can close this once he's confirmed all's good.

**Comment by cgrandin** [comment] 2018-02-05 19:15
I'm getting 1,398,000 for that calculation. I got the same earlier, so I deleted all the RData files and re-ran build(T,T,T), but am still getting 1,398,000.

I think I forgot to download the base model again since the change so I will try again.

**Comment by aaronmberger** [comment] 2018-02-05 19:21
And remember the mcmc folder copying step:

From Ian above:
"Yes, we could likely close this, but maybe should leave open until Andy and Chris have a chance to move the 2018.40_base_model/mcmc_24mil-grandin (or whatever it was called), into old_mcmc or some other location and download
2018.42_fix_survey_log-theta/mcmc
and copy that into
2018.40_base_model/mcmc"

**Comment by taylori** [comment] 2018-02-05 19:23
I should have added that the 2018.40_base_model/mcmc on Google Drive has already been updated to be correct, but if anyone downloaded that folder before Saturday, it would be the old version

**Comment by aaronmberger** [comment] 2018-02-05 19:29
My alternative seed (same starting values) 24 mil mcmc has finished and I will look into multi-chain diagnostics just as a second extra double check for convergence.  Though our normal diagnostics look quite good anyway.

**Comment by cgrandin** [comment] 2018-02-05 20:48
I finally have the right number, and will go ahead and start on the issues.

**Comment by taylori** [comment] 2018-02-05 20:50
Excellent. I think you can close this Feb 1 issue now.

**Comment by aaronmberger** [comment] 2018-02-06 17:08
My document is still not building properly.  Chris can you help?  I keep getting an error associated with not being able to allocate a vector of 1.2GB.  I feel like I had a similar error last year, but now can't recall how I got around it.  I wouldn't think required memory would have increased much from last year (although I guess our #mcmc samples doubled).  Any thoughts?

**Comment by cgrandin** [comment] 2018-02-06 17:18
The first thing I would do is go into R and do this:

`source("all.r");load.models.into.parent.env();source("custom-knitr-variables.r")`

so that you can see what is causing the error. Let me know what happens 

Just a reminder there is section a section in the Readme.md for this repo

**Comment by andrew-edwards** [comment] 2018-02-06 17:25
I feel like the document is taking longer to build than last week, which I assumed was because of the 2000 MCMC samples (though that isn't huge).

**Comment by aaronmberger** [comment] 2018-02-06 18:11
The figure (a retro plot) where the knitr crashes builds just fine when run independently.  Here is a copy of where it falls apart and the output when using traceback()

%%%%%%%%%%%%%%%%%%%%%%%
\begin{figure}[H]
\begin{center}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{knitr-cache/main_biomass_recruitment_retrospective-1} 

\end{knitrout}
\end{center}
\caption{Estimates of spawning biomass at the start of each year (top)
  and recruitment (bottom) for the base model and retrospective runs
  (based on MLE model runs).}
\label{fig:main-biomass-recruitment-retrospective}
\end{figure}
%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%
\begin{figure}[H]
\begin{center}






Quitting from lines 1207-1219 (./main-figures/main-figures.rnw) 
Quitting from lines 276-308 (./main-figures/main-figures.rnw) 
Error: cannot allocate vector of size 1.2 Gb
In addition: There were 50 or more warnings (use warnings() to see the first 50)


> traceback()
20: lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress, 
        envhook)
19: getFromNamespace("makeLazyLoadDB", "tools")(knit_global(), path, 
        variables = keys)
18: cache$save(objects, outname, hash, lazy = options$cache.lazy)
17: block_cache(options, output, objs)
16: block_exec(params)
15: call_block(x)
14: process_group.block(group)
13: process_group(group)
12: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
        error = function(e) {
            setwd(wd)
            cat(res, sep = "\n", file = output %n% "")
            message("Quitting from lines ", paste(current_lines(i), 
                collapse = "-"), " (", knit_concord$get("infile"), 
                ") ")
        })
11: process_file(text, output)
10: knit(..., tangle = opts_knit$get("tangle"), envir = envir, encoding = opts_knit$get("encoding") %n% 
        getOption("encoding"))
9: FUN(X[[i]], ...)
8: lapply(sc_split(params$child), knit_child, options = block$params)
7: call_block(x)
6: process_group.block(group)
5: process_group(group)
4: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
       error = function(e) {
           setwd(wd)
           cat(res, sep = "\n", file = output %n% "")
           message("Quitting from lines ", paste(current_lines(i), 
               collapse = "-"), " (", knit_concord$get("infile"), 
               ") ")
       })
3: process_file(text, output)
2: knit(paste0(doc.name, ".rnw")) at utilities.r#16
1: build.doc()

**Comment by andrew-edwards** [comment] 2018-02-06 18:20
Presumably you did
```build(run.retro=FALSE)```
after changing the number of years.  Just throwing it out there ;)

**Comment by cgrandin** [comment] 2018-02-06 18:26
Hey Aaron, that's all knitr output and won't help you. Launch R in the same place where you do `build()` and do this:
`source("all.r");load.models.into.parent.env();source("custom-knitr-variables.r")`

It loads everything the same as in the document so that you can try the code directly in the terminal. If you do that, then cut and paste the function calls between those lines it suggests into the R window you can narrow it down to which function is failing

**Comment by aaronmberger** [comment] 2018-02-06 18:40
I'll try that again.  I did that previously and went in and ran the functions (not knitr stuff) between the lines specified in the error:
Quitting from lines 1207-1219 (./main-figures/main-figures.rnw)
Quitting from lines 276-308 (./main-figures/main-figures.rnw)

And got the correct figures output.

**Comment by cgrandin** [comment] 2018-02-06 18:47
Try this command in R:
`memory.limit()`
it is in MB so maybe yours is only 1200?
you can increase it  like this:
`memory.limit(size=2000)`
or whatever amount you want

If that's not it, it could also be that you are using 32-bit R and in that case I'd switch to 64-bit

**Comment by aaronmberger** [comment] 2018-02-06 19:28
Bloody hell - it finally built!

Thanks Chris - my suspicion that it was memory related was correct and thanks for the path to increase it.  My memory.limit was already at 8900 and I had to increase it to 15000 (got tired of incremental increases and went for the big jump) for it to run.  I had been using 64 bit all along...

**Closed by aaronmberger** 2018-02-06 19:28 UTC

**Comment by cgrandin** [comment] 2018-02-06 19:46
Great, glad to see you're back on track :+1:
