### ISSUE TITLE
Go ahead and build the doc.. We are doing so and will go through it

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#105] opened 2016-02-09 00:43 UTC
Once we agree, I can create a preSRG release, which uses GitHub tags to store the state of the project at this point in time.

**Comment by allan-hicks** [comment] 2016-02-09 00:44
Do you mind posting apdf on Google Drive. I would like to do a quick
comparison just to make sure I am doing the workflow correctly.  pdf is
fine.

**Comment by aaronmberger** [comment] 2016-02-09 00:45
Still a few ** in glossary

**Comment by cgrandin** [comment] 2016-02-09 00:49
We are getting those now...

**Comment by allan-hicks** [comment] 2016-02-09 00:49
Here is the bibtex entry for Stewart et al, which is referenced in the
glossary:

@article{Stewart201337,
title = "A comparison of stock assessment uncertainty estimates using
maximum likelihood and Bayesian methods implemented with the same model
framework ",
journal = "Fisheries Research ",
volume = "142",
number = "",
pages = "37 - 46",
year = "2013",
note = "",
issn = "0165-7836",
doi = "http://dx.doi.org/10.1016/j.fishres.2012.07.003",
url = "http://www.sciencedirect.com/science/article/pii/S0165783612002081",
author = "Ian J. Stewart and Allan C. Hicks and Ian G. Taylor and James T.
Thorson and Chantell Wetzel and Sven Kupschus",
keywords = "Maximum-likelihood",
keywords = "Bayesian",
keywords = "Uncertainty",
keywords = "Stock assessment ",
abstract = "Many fisheries stock assessment models are implemented
specifically for likelihood-based estimation or for Bayesian inference (via
full integration of the joint posterior distributions), but not all have
appropriate structure for both statistical approaches. Bias correction of
recruitment deviations, in particular, must be adjusted to achieve
consistency in each case. Fisheries management often uses the two types of
results similarly, setting future catch quotas based on expected values or
posterior medians depending on which is available given time constraints.
Using two recent examples from the U.S. west coast, Pacific hake and
sablefish, both implemented in Stock Synthesis, we find that
likelihood-based estimates of key management quantities, such as spawning
biomass, corresponded well with posterior modes, but tend to be lower (on
an absolute scale) than posterior median values and that the asymptotic
approximation for uncertainty intervals based on the Hessian matrix tends
to overestimate the likelihood of smaller stock sizes and underestimate
that of larger stock sizes. This pattern may be caused by a basic asymmetry
in most fisheries data-sets: the necessity of a minimum stock size to have
generated the observed catch/time-series, but little information regarding
the plausibility among much larger stock sizes. Where only one type of
inference is available, this asymmetry may be important for management
decision-making. Even if management takes explicit account of uncertainty,
in some cases adding a precautionary buffer that scales with the relative
uncertainty in point estimates, the differences in catch advice may turn
out to be important and the relative reductions non-linear. "
}

**Comment by minnowslayer** [comment] 2016-02-09 00:53
i've done all that all be able to on this for now.  Thanks so much for your
efforts getting all latex knitr together!

**Comment by cgrandin** [comment] 2016-02-09 00:53
Ok, we are almost there. I'll post a PDF as soon as I merge these changes and build. Should be less than 10 mins.

**Comment by andrew-edwards** [comment] 2016-02-09 00:53
Doing the bibtex. Are all the ** gone inthe main text?

**Comment by allan-hicks** [comment] 2016-02-09 00:55
I only see ** in the glossary of the build I just did. So, looking good.

**Comment by aaronmberger** [comment] 2016-02-09 00:57
some new additions to sensitivity section seem incorrect ("2016 estimates at 0.8% of unfished biomass for the base model and 1% for the age-1 index").  I

**Comment by cgrandin** [comment] 2016-02-09 00:58
If you can fix it, there's still time

**Comment by allan-hicks** [comment] 2016-02-09 00:59
I tried to generalize it. Need to multiply those by 100. Just do that in
the Sexpr

**Comment by allan-hicks** [comment] 2016-02-09 00:59
Good catch Aaron!

**Comment by cgrandin** [comment] 2016-02-09 00:59
and, use fmt0(val, 1) to make it nice

**Comment by cgrandin** [comment] 2016-02-09 01:00
I'll wait for your commit

**Comment by aaronmberger** [comment] 2016-02-09 01:02
just did commit, but only removed \%

didn't see this until after

On Mon, Feb 8, 2016 at 5:00 PM, cgrandin <notifications@github.com> wrote:

> I'll wait for your commit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/105#issuecomment-181650165>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment] 2016-02-09 01:02
Committed. And, I should be because I really messed that one up.

**Comment by aaronmberger** [comment] 2016-02-09 01:03
I thought for a moment there we switched over to Pacific bluefin!

**Comment by allan-hicks** [comment] 2016-02-09 01:03
I assume that Master Chris can sort this out.

**Comment by allan-hicks** [comment] 2016-02-09 01:04
You are still gun shy, I see.

**Comment by allan-hicks** [comment] 2016-02-09 01:06
Chris, note that I corrected another error besides the %'s.  You should
choose my changes over Aaron's since I found an additional error.

**Comment by cgrandin** [comment] 2016-02-09 01:07
Yep, I did so. Building now. Will get back to you in a couple minutes

**Comment by andrew-edwards** [comment] 2016-02-09 01:09
We agreed on line numbers on yes? It all works fine (as long you latex three times after bibtex, if you delete the .bbl each time [which you shouldn't really]). Works fine on mine.

**Comment by allan-hicks** [comment] 2016-02-09 01:15
For the sensitivity section, we can manually enter numbers if needed. I
just got an error. Let me know if you want the numbers.

**Comment by allan-hicks** [comment] 2016-02-09 01:16
Or, I thik the 100* needs to be within fmt0.  I was using round earlier

**Comment by andrew-edwards** [comment] 2016-02-09 01:16
Sounds like it. And that's what's freaking Chris out right now. 
Think he's found it.

**Comment by allan-hicks** [comment] 2016-02-09 01:17
I jsut made a commit

**Comment by allan-hicks** [comment] 2016-02-09 01:18
My commit seems to be working (knitting)

**Comment by allan-hicks** [comment] 2016-02-09 01:20
My build with my recent commit looks OK

**Comment by cgrandin** [comment] 2016-02-09 01:30
Ok, I put the build on the google drive... Check it out, What should we do now? I can create a release on github if we are happy with it.

**Comment by allan-hicks** [comment] 2016-02-09 01:31
I'll have a 2-minute look through. Then, email it to Miako and she will
distribute.

**Comment by allan-hicks** [comment] 2016-02-09 01:35
Looks good to me!
Great job. It is always tough on the last day, especially when you have no
internet.
Thanks.
Allan

**Comment by cgrandin** [comment] 2016-02-09 01:37
Ok, Andy has the line numbering better than mine, so he will post his on the Google drive, so please use that one. Thanks all for the hard work!

**Comment by allan-hicks** [comment] 2016-02-09 01:38
Great. And, can you email a copy to Miako? She doesn't have access to our
Google Drive. Or, I can download it and email it to her if you have any
issues.

**Comment by cgrandin** [comment] 2016-02-09 01:42
We don't have email, so if you could do that we'd appreciate it. Thanks!

**Comment by andrew-edwards** [comment] 2016-02-09 01:42
Mine and Chris's had identical pages (I checked each page), except his line numbers got out of whack. So use mine.....

**Comment by aaronmberger** [comment] 2016-02-09 01:43
Nice work all!

On Monday, February 8, 2016, Allan C Hicks <notifications@github.com> wrote:

> Great. And, can you email a copy to Miako? She doesn't have access to our
> Google Drive. Or, I can download it and email it to her if you have any
> issues.
>
> On Mon, Feb 8, 2016 at 5:37 PM, cgrandin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Ok, Andy has the line numbering better than mine, so he will post his on
> > the Google drive, so please use that one. Thanks all for the hard work!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgrandin/hake-assessment/issues/105#issuecomment-181661257
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/105#issuecomment-181661823>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by andrew-edwards** [comment] 2016-02-09 01:46
Excellent. Bit hectic at the end, and sorry we were out of touch for a while, but we got there. I think we had enough eyes on everything that things are good. Our roles kind of evolved.... Chris is finishing his beer and then I think we're done.

**Comment by andrew-edwards** [comment] 2016-02-09 01:49
So, Allan, you'll submit yes? No more changes. 
If something really needs changing then do an issue and we'll check in at 8:30pm. Else, we're done.
Cheers....

**Comment by allan-hicks** [comment] 2016-02-09 01:49
Nice.  It is always hectic at the end. One year, Ian Stewart and I thought
we were done at 3pm.  It wasn't until 5:30 that we sent the document due to
pdf conversion issues.  Last year, Ian Taylor and I had a bunch of last
minute things.  The good thing is that we have a really good document, and
we can mess with the details over the next few weeks.

Get some rest, and we'll talk about the SRG soon.
Allan

**Comment by andrew-edwards** [comment] 2016-02-09 01:50
Great. Just let us know when you've sent the email.

**Comment by allan-hicks** [comment] 2016-02-09 01:51
Already sent to Miako, who is waiting for it.  I cc'ed your DFO accounts,
so that you don't have to worry about it! Out of sight, out of mind!

**Comment by andrew-edwards** [comment] 2016-02-09 01:51
Excellent. We are done.

**Comment by allan-hicks** [comment] 2016-02-09 01:53
She has it and has uploaded it to the SRG google Drive folder:

https://drive.google.com/a/noaa.gov/folderview?id=0B8vORV3L9mJJNDFCeGs2MVlHaWc&usp=drive_web#

Have a good night,
Allan

**Comment by andrew-edwards** [comment] 2016-02-09 01:54
Cheers. We even got the email! No need to check in tonight - have a good one.

**Closed** 2016-02-09 02:40 UTC
